/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyPredictionsRouteImport } from './routes/my-predictions'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ChampionRouteImport } from './routes/champion'
import { Route as IndexRouteImport } from './routes/index'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPredictionsRoute = MyPredictionsRouteImport.update({
  id: '/my-predictions',
  path: '/my-predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionRoute = ChampionRouteImport.update({
  id: '/champion',
  path: '/champion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champion': typeof ChampionRoute
  '/matches': typeof MatchesRoute
  '/my-predictions': typeof MyPredictionsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champion': typeof ChampionRoute
  '/matches': typeof MatchesRoute
  '/my-predictions': typeof MyPredictionsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champion': typeof ChampionRoute
  '/matches': typeof MatchesRoute
  '/my-predictions': typeof MyPredictionsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/rules': typeof RulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/champion'
    | '/matches'
    | '/my-predictions'
    | '/profile'
    | '/ranking'
    | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champion'
    | '/matches'
    | '/my-predictions'
    | '/profile'
    | '/ranking'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/champion'
    | '/matches'
    | '/my-predictions'
    | '/profile'
    | '/ranking'
    | '/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionRoute: typeof ChampionRoute
  MatchesRoute: typeof MatchesRoute
  MyPredictionsRoute: typeof MyPredictionsRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-predictions': {
      id: '/my-predictions'
      path: '/my-predictions'
      fullPath: '/my-predictions'
      preLoaderRoute: typeof MyPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champion': {
      id: '/champion'
      path: '/champion'
      fullPath: '/champion'
      preLoaderRoute: typeof ChampionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionRoute: ChampionRoute,
  MatchesRoute: MatchesRoute,
  MyPredictionsRoute: MyPredictionsRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
